CI/CD SIMTA

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -15,41 +15,41 @@ env:
   GO_VERSION: "1.23"
 
 jobs:
-  # SAST - CodeQL (GitHub Native)
-  sast-codeql:
-    name: SAST dengan CodeQL (Go + JS)
-    runs-on: ubuntu-latest
+  # # SAST - CodeQL (GitHub Native)
+  # sast-codeql:
+  #   name: SAST dengan CodeQL (Go + JS)
+  #   runs-on: ubuntu-latest
 
-    steps:
-      - name: Checkout source code
-        uses: actions/checkout@v4
+  #   steps:
+  #     - name: Checkout source code
+  #       uses: actions/checkout@v4
 
-      - name: Setup Go
-        uses: actions/setup-go@v5
-        with:
-          go-version: 1.23
+  #     - name: Setup Go
+  #       uses: actions/setup-go@v5
+  #       with:
+  #         go-version: 1.23
 
-      - name: Initialize CodeQL
-        uses: github/codeql-action/init@v3
-        with:
-          languages: go, javascript
+  #     - name: Initialize CodeQL
+  #       uses: github/codeql-action/init@v3
+  #       with:
+  #         languages: go, javascript
 
-      - name: Perform CodeQL Analysis
-        uses: github/codeql-action/analyze@v3
-        with:
-          output: codeql-results
+  #     - name: Perform CodeQL Analysis
+  #       uses: github/codeql-action/analyze@v3
+  #       with:
+  #         output: codeql-results
 
-      # === Gate Severity Critical ===
-      - name: Fail on Critical findings
-        run: |
-          echo "Checking for Critical vulnerabilities..."
-          # Grep file SARIF untuk severity=CRITICAL
-          if grep -q '"level": "error"' codeql-results/*.sarif; then
-            echo "Found Critical vulnerabilities in CodeQL scan!"
-            exit 1
-          else
-            echo "No Critical vulnerabilities found."
-          fi
+  #     # === Gate Severity Critical ===
+  #     - name: Fail on Critical findings
+  #       run: |
+  #         echo "Checking for Critical vulnerabilities..."
+  #         # Grep file SARIF untuk severity=CRITICAL
+  #         if grep -q '"level": "error"' codeql-results/*.sarif; then
+  #           echo "Found Critical vulnerabilities in CodeQL scan!"
+  #           exit 1
+  #         else
+  #           echo "No Critical vulnerabilities found."
+  #         fi
 
 #   # DEPENDENCY SCAN (govulncheck)
 #   dep-scan:
@@ -144,22 +144,22 @@ jobs:
 #       - name: Push Image
 #         run: docker push smgxv/ta-service
 
-#   build-user-service:
-#     needs: image-scan
-#     name: Build User Service Image
-#     runs-on: ubuntu-latest
-#     steps:
-#       - name: Checkout
-#         uses: actions/checkout@v2
-#       - name: Build Image
-#         run: docker build -t smgxv/user-service -f user_service/Dockerfile user_service
-#       - name: Login to DockerHub
-#         uses: docker/login-action@v1
-#         with:
-#           username: ${{ secrets.DOCKERHUB_USERNAME }}
-#           password: ${{ secrets.DOCKERHUB_TOKEN }}
-#       - name: Push Image
-#         run: docker push smgxv/user-service
+  build-user-service:
+    # needs: image-scan
+    name: Build User Service Image
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2
+      - name: Build Image
+        run: docker build -t smgxv/user-service -f user_service/Dockerfile user_service
+      - name: Login to DockerHub
+        uses: docker/login-action@v1
+        with:
+          username: ${{ secrets.DOCKERHUB_USERNAME }}
+          password: ${{ secrets.DOCKERHUB_TOKEN }}
+      - name: Push Image
+        run: docker push smgxv/user-service
 
 #   build-document-service:
 #     needs: image-scan
@@ -214,23 +214,23 @@ jobs:
 #             docker run -d -p 8080:8080 --name ta-service smgxv/ta-service
 #             docker network connect simta_net ta-service
 
-#   deploy-user-service:
-#     needs: build-user-service
-#     runs-on: ubuntu-latest
-#     steps:
-#       - name: Deploy User Service to VPS
-#         uses: appleboy/ssh-action@master
-#         with:
-#           host: ${{ secrets.VPS_HOST }}
-#           username: ${{ secrets.VPS_USERNAME }}
-#           password: ${{ secrets.VPS_PASSWORD }}
-#           port: ${{ secrets.VPS_PORT }}
-#           script: |
-#             docker stop user-service || true && docker rm user-service || true
-#             docker system prune -af
-#             docker pull smgxv/user-service
-#             docker run -d -p 8081:8081 --name user-service smgxv/user-service
-#             docker network connect simta_net user-service
+  deploy-user-service:
+    needs: build-user-service
+    runs-on: ubuntu-latest
+    steps:
+      - name: Deploy User Service to VPS
+        uses: appleboy/ssh-action@master
+        with:
+          host: ${{ secrets.VPS_HOST }}
+          username: ${{ secrets.VPS_USERNAME }}
+          password: ${{ secrets.VPS_PASSWORD }}
+          port: ${{ secrets.VPS_PORT }}
+          script: |
+            docker stop user-service || true && docker rm user-service || true
+            docker system prune -af
+            docker pull smgxv/user-service
+            docker run -d -p 8081:8081 --name user-service smgxv/user-service
+            docker network connect simta_net user-service
 
 #   deploy-document-service:
 #     needs: build-document-service
