CI/CD SIMTA

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -38,135 +38,135 @@ jobs:
   #       uses: github/codeql-action/analyze@v3
 
   #DEPENDENCY SCAN (govulncheck)
-  dep-scan:
-    # needs: sast-codeql
-    name: Govulncheck (${{ matrix.service.name }})
-    runs-on: ubuntu-latest
-    strategy:
-      fail-fast: false
-      matrix:
-        service:
-          - { name: ta-service,           path: ta_service }
-          - { name: user-service,         path: user_service }
-          - { name: document-service,     path: document_service }
-          - { name: notification-service, path: notification_service }
+  # dep-scan:
+  #   # needs: sast-codeql
+  #   name: Govulncheck (${{ matrix.service.name }})
+  #   runs-on: ubuntu-latest
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       service:
+  #         - { name: ta-service,           path: ta_service }
+  #         - { name: user-service,         path: user_service }
+  #         - { name: document-service,     path: document_service }
+  #         - { name: notification-service, path: notification_service }
 
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v4
 
-      # Gate + simpan laporan TEXT
-      - name: Govulncheck (gate + save text report)
-        uses: golang/govulncheck-action@v1
-        with:
-          go-version-input: ${{ env.GO_VERSION }}         
-          work-dir: ${{ matrix.service.path }}             
-          go-package: ./...                                
-          output-format: text                              
-          output-file: ${{ matrix.service.name }}-govulncheck.txt
-          repo-checkout: false
-          cache: true
-          cache-dependency-path: ${{ matrix.service.path }}/go.sum
+  #     # Gate + simpan laporan TEXT
+  #     - name: Govulncheck (gate + save text report)
+  #       uses: golang/govulncheck-action@v1
+  #       with:
+  #         go-version-input: ${{ env.GO_VERSION }}         
+  #         work-dir: ${{ matrix.service.path }}             
+  #         go-package: ./...                                
+  #         output-format: text                              
+  #         output-file: ${{ matrix.service.name }}-govulncheck.txt
+  #         repo-checkout: false
+  #         cache: true
+  #         cache-dependency-path: ${{ matrix.service.path }}/go.sum
 
-      # Arsipkan laporan TEXT
-      - name: Upload govulncheck report (artifact)
-        if: always()
-        uses: actions/upload-artifact@v4
-        with:
-          name: govulncheck-${{ matrix.service.name }}
-          path: ${{ matrix.service.name }}-govulncheck.txt
+  #     # Arsipkan laporan TEXT
+  #     - name: Upload govulncheck report (artifact)
+  #       if: always()
+  #       uses: actions/upload-artifact@v4
+  #       with:
+  #         name: govulncheck-${{ matrix.service.name }}
+  #         path: ${{ matrix.service.name }}-govulncheck.txt
 
 
-  # IMAGE SCAN (trivy)
-  image-scan:
-    needs: dep-scan
-    name: Image Scan (${{ matrix.service.name }})
-    runs-on: ubuntu-latest
-    strategy:
-      fail-fast: false
-      matrix:
-        service:
-          - { name: ta-service,           path: ta_service,           dockerfile: ta_service/Dockerfile }
-          - { name: user-service,         path: user_service,         dockerfile: user_service/Dockerfile }
-          - { name: document-service,     path: document_service,     dockerfile: document_service/Dockerfile }
-          - { name: notification-service, path: notification_service, dockerfile: notification_service/Dockerfile }
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
+  # # IMAGE SCAN (trivy)
+  # image-scan:
+  #   needs: dep-scan
+  #   name: Image Scan (${{ matrix.service.name }})
+  #   runs-on: ubuntu-latest
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       service:
+  #         - { name: ta-service,           path: ta_service,           dockerfile: ta_service/Dockerfile }
+  #         - { name: user-service,         path: user_service,         dockerfile: user_service/Dockerfile }
+  #         - { name: document-service,     path: document_service,     dockerfile: document_service/Dockerfile }
+  #         - { name: notification-service, path: notification_service, dockerfile: notification_service/Dockerfile }
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v4
 
-      - name: Build image (local daemon)
-        run: |
-          docker build \
-            -f "${{ matrix.service.dockerfile }}" \
-            -t "${{ matrix.service.name }}:scan" \
-            "${{ matrix.service.path }}"
+  #     - name: Build image (local daemon)
+  #       run: |
+  #         docker build \
+  #           -f "${{ matrix.service.dockerfile }}" \
+  #           -t "${{ matrix.service.name }}:scan" \
+  #           "${{ matrix.service.path }}"
 
-      - name: Trivy Image scan (gate)
-        uses: aquasecurity/trivy-action@0.28.0
-        with:
-          image-ref: ${{ matrix.service.name }}:scan
-          format: table
-          vuln-type: os,library
-          ignore-unfixed: true
-          severity: CRITICAL      
-          exit-code: '1'          
-          hide-progress: true
-          timeout: 10m
+  #     - name: Trivy Image scan (gate)
+  #       uses: aquasecurity/trivy-action@0.28.0
+  #       with:
+  #         image-ref: ${{ matrix.service.name }}:scan
+  #         format: table
+  #         vuln-type: os,library
+  #         ignore-unfixed: true
+  #         severity: CRITICAL      
+  #         exit-code: '1'          
+  #         hide-progress: true
+  #         timeout: 10m
 
  # Build Image ()
-  build-ta-service:
-    needs: image-scan
-    name: Build Image
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v2
-      - name: Build Image
-        run: docker build -t smgxv/ta-service -f ta_service/Dockerfile ta_service
-      - name: Login to DockerHub
-        uses: docker/login-action@v1
-        with:
-          username: ${{ secrets.DOCKERHUB_USERNAME }}
-          password: ${{ secrets.DOCKERHUB_TOKEN }}
-      - name: Push Image
-        run: docker push smgxv/ta-service
+  # build-ta-service:
+  #   needs: image-scan
+  #   name: Build Image
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v2
+  #     - name: Build Image
+  #       run: docker build -t smgxv/ta-service -f ta_service/Dockerfile ta_service
+  #     - name: Login to DockerHub
+  #       uses: docker/login-action@v1
+  #       with:
+  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
+  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
+  #     - name: Push Image
+  #       run: docker push smgxv/ta-service
 
-  build-user-service:
-    needs: image-scan
-    name: Build User Service Image
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v2
-      - name: Build Image
-        run: docker build -t smgxv/user-service -f user_service/Dockerfile user_service
-      - name: Login to DockerHub
-        uses: docker/login-action@v1
-        with:
-          username: ${{ secrets.DOCKERHUB_USERNAME }}
-          password: ${{ secrets.DOCKERHUB_TOKEN }}
-      - name: Push Image
-        run: docker push smgxv/user-service
+  # build-user-service:
+  #   needs: image-scan
+  #   name: Build User Service Image
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v2
+  #     - name: Build Image
+  #       run: docker build -t smgxv/user-service -f user_service/Dockerfile user_service
+  #     - name: Login to DockerHub
+  #       uses: docker/login-action@v1
+  #       with:
+  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
+  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
+  #     - name: Push Image
+  #       run: docker push smgxv/user-service
 
-  build-document-service:
-    needs: image-scan
-    name: Build Document Service Image
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v2
-      - name: Build Image
-        run: docker build -t smgxv/document-service -f document_service/Dockerfile document_service
-      - name: Login to DockerHub
-        uses: docker/login-action@v1
-        with:
-          username: ${{ secrets.DOCKERHUB_USERNAME }}
-          password: ${{ secrets.DOCKERHUB_TOKEN }}
-      - name: Push Image
-        run: docker push smgxv/document-service
+  # build-document-service:
+  #   needs: image-scan
+  #   name: Build Document Service Image
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v2
+  #     - name: Build Image
+  #       run: docker build -t smgxv/document-service -f document_service/Dockerfile document_service
+  #     - name: Login to DockerHub
+  #       uses: docker/login-action@v1
+  #       with:
+  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
+  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
+  #     - name: Push Image
+  #       run: docker push smgxv/document-service
 
   build-notification-service:
-    needs: image-scan
+    # needs: image-scan
     name: Build Notification Service Image
     runs-on: ubuntu-latest
     steps:
@@ -182,60 +182,60 @@ jobs:
       - name: Push Image
         run: docker push smgxv/notification-service
 
-  # Deploy ke lingkungan sementara
-  deploy-ta-service:
-    needs: build-ta-service
-    runs-on: ubuntu-latest
-    steps:
-      - name: Deploy to VPS
-        uses: appleboy/ssh-action@master
-        with:
-          host: ${{ secrets.VPS_HOST }}
-          username: ${{ secrets.VPS_USERNAME }}
-          password: ${{ secrets.VPS_PASSWORD }}
-          port: ${{ secrets.VPS_PORT }}
-          script: |
-            docker stop ta-service || true && docker rm ta-service || true
-            docker system prune -af
-            docker pull smgxv/ta-service
-            docker run -d -p 8080:8080 --name ta-service smgxv/ta-service
-            docker network connect simta_net ta-service
+  # # Deploy ke lingkungan sementara
+  # deploy-ta-service:
+  #   needs: build-ta-service
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Deploy to VPS
+  #       uses: appleboy/ssh-action@master
+  #       with:
+  #         host: ${{ secrets.VPS_HOST }}
+  #         username: ${{ secrets.VPS_USERNAME }}
+  #         password: ${{ secrets.VPS_PASSWORD }}
+  #         port: ${{ secrets.VPS_PORT }}
+  #         script: |
+  #           docker stop ta-service || true && docker rm ta-service || true
+  #           docker system prune -af
+  #           docker pull smgxv/ta-service
+  #           docker run -d -p 8080:8080 --name ta-service smgxv/ta-service
+  #           docker network connect simta_net ta-service
 
-  deploy-user-service:
-    needs: build-user-service
-    runs-on: ubuntu-latest
-    steps:
-      - name: Deploy User Service to VPS
-        uses: appleboy/ssh-action@master
-        with:
-          host: ${{ secrets.VPS_HOST }}
-          username: ${{ secrets.VPS_USERNAME }}
-          password: ${{ secrets.VPS_PASSWORD }}
-          port: ${{ secrets.VPS_PORT }}
-          script: |
-            docker stop user-service || true && docker rm user-service || true
-            docker system prune -af
-            docker pull smgxv/user-service
-            docker run -d -p 8081:8081 --name user-service smgxv/user-service
-            docker network connect simta_net user-service
+  # deploy-user-service:
+  #   needs: build-user-service
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Deploy User Service to VPS
+  #       uses: appleboy/ssh-action@master
+  #       with:
+  #         host: ${{ secrets.VPS_HOST }}
+  #         username: ${{ secrets.VPS_USERNAME }}
+  #         password: ${{ secrets.VPS_PASSWORD }}
+  #         port: ${{ secrets.VPS_PORT }}
+  #         script: |
+  #           docker stop user-service || true && docker rm user-service || true
+  #           docker system prune -af
+  #           docker pull smgxv/user-service
+  #           docker run -d -p 8081:8081 --name user-service smgxv/user-service
+  #           docker network connect simta_net user-service
 
-  deploy-document-service:
-    needs: build-document-service
-    runs-on: ubuntu-latest
-    steps:
-      - name: Deploy Document Service to VPS
-        uses: appleboy/ssh-action@master
-        with:
-          host: ${{ secrets.VPS_HOST }}
-          username: ${{ secrets.VPS_USERNAME }}
-          password: ${{ secrets.VPS_PASSWORD }}
-          port: ${{ secrets.VPS_PORT }}
-          script: |
-            docker stop document-service || true && docker rm document-service || true
-            docker system prune -af
-            docker pull smgxv/document-service
-            docker run -d -p 8082:8082 --name document-service smgxv/document-service
-            docker network connect simta_net document-service
+  # deploy-document-service:
+  #   needs: build-document-service
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Deploy Document Service to VPS
+  #       uses: appleboy/ssh-action@master
+  #       with:
+  #         host: ${{ secrets.VPS_HOST }}
+  #         username: ${{ secrets.VPS_USERNAME }}
+  #         password: ${{ secrets.VPS_PASSWORD }}
+  #         port: ${{ secrets.VPS_PORT }}
+  #         script: |
+  #           docker stop document-service || true && docker rm document-service || true
+  #           docker system prune -af
+  #           docker pull smgxv/document-service
+  #           docker run -d -p 8082:8082 --name document-service smgxv/document-service
+  #           docker network connect simta_net document-service
 
   deploy-notification-service:
     needs: build-notification-service
